### ISSUE TITLE
in one button print

### ISSUE THREAD

**Issue by fajarazay** [yefengfreedom/BtPrinter#1]
why if i put printTest(); and printBitmapTest(); in one button won't print?

**Comment by yefengjie** [comment]
sorry, I don't catch your meaning

**Comment by fajarazay** [comment]
I mean, why if I call function to print text and print image (bitmap) by one button, it doesn't work?
and then I have second question, if use two button  to print text and print image. why when I print bitmap from resource imageview, it's only work once? the second click is not.
