### ISSUE TITLE
我clone了你的项目，为啥运行无法搜索蓝牙设备

### ISSUE THREAD

**Issue by JackRo** [yefengfreedom/BtPrinter#2]
在你的第一个activity里，点击尚未绑定蓝牙设备，进入第二个activity，搜索蓝牙设备，为啥附近有蓝牙设备开启，仍然无法搜索到蓝牙设备？

**Comment by yefengjie** [comment]
你可以打开手机蓝牙试试，如果手机自带的蓝牙都搜索不到，那app自然也搜索不到~
可能是蓝牙匹配问题
