### ISSUE TITLE
How we can append text with Image 

### ISSUE THREAD

**Issue by mrcodecloud** [yefengfreedom/BtPrinter#6]
I want to print image ( QR Code ) and it's Text, alligned in the middle of paper and text after image in next line. I did try two things
1. Adding text to the image call for printer
2. Calling printing service immediately for text after calling printing service for image

both didn't worked. Can you help please ?

**Comment by yefengjie** [comment]
I think the second way should work, but I didn't try it.
how about take a little time sleep and reset printer:
Thread.sleep(300)
printBytes.add(GPrinterCommand.reset);
printBytes.add(GPrinterCommand.print);
PrintQueue.getQueue(getApplicationContext()).add(bytes);
then you can calling print text command after doing this

**Comment by mrcodecloud** [comment]
@yefengjie Thank you very much for your kind response.
I will try the Thread.sleep and report back to you it's output. 

How i can align the image/text to the middle of paper ?

**Comment by yefengjie** [comment]
you can check the printer command doc. Each printer command is not always the same, you should find your printer tech doc or just ask their tech service

**Comment by mrcodecloud** [comment]
Ok Sir,
Thank you very much

**Comment by yefengjie** [comment]
you are welcome~
