### ISSUE TITLE
Printing Image Too Dark Problem

### ISSUE THREAD

**Issue by carrlin009** [yefengfreedom/BtPrinter#7]
Hello Sir, When I try to print Pic using your code via POS 80mm Xprinter, the printed image comes out too dark version. I have tested it out using PNG image and image including text but all included images and text became too dark in the print-outs. 
I just want the text remained normal (think and clear) in the print-outs.

Could you kindly please help me out sir.
Thanks.

**Comment by yefengjie** [comment]
this maybe the Xprinter's problem, you try to concat the Xprinter's manufacturers, and ask for their help or use their demo apps

**Comment by carrlin009** [comment]
Thank you for your kind reply Sir
In my testing experience, I have also tested another quick printer apk too on same printer xprinter.
The result was normal style text and not bold and size was 200 px and 200 px size with is tiny in 80mm paper.
If you have sometime please help me to solve bold issue.
waiting your kind reply.
Thanks a lot

**Comment by yefengjie** [comment]
each printer's print code is not the same, my demo is use gprinter's print command code, you should check the your Xprinter's print command code
